#!/usr/bin/env sh
#
# Tune powersaving parameters based on whether the AC adaptor is connected or
# disconnected.
#
# NOTE: This probably only makes sense if the powersave CPU governer is enabled?
#
# Usage: ac_adaptor {disconnected | connected}

connected() {
    # AC adaptor is connect; adjust accordingly.

    echo "AC adaptor connected!"

    CPUFREQ_PATH="/sys/devices/system/cpu/cpu0/cpufreq"
    cat "${CPUFREQ_PATH}/cpuinfo_max_freq" > "${CPUFREQ_PATH}/scaling_max_freq"

}

disconnected() {
    # AC adaptor is disconnected; adjust accordingly.

    echo "AC adaptor disconnected!"

    CPUFREQ_PATH="/sys/devices/system/cpu/cpu0/cpufreq"
    cat "${CPUFREQ_PATH}/cpuinfo_min_freq" > "${CPUFREQ_PATH}/scaling_max_freq"

}

case "$1" in
    connected) connected; break;;
    disconnected) disconnected; break;;
    *) echo "Unknown event type '$1'!"; exit 1;;
esac
